// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgGVNG287PiT18lgUPRo8EpzofZfokB0A',
    appId: '1:980448378951:web:e90a7107ae198e2ad2b162',
    messagingSenderId: '980448378951',
    projectId: 'budgetbee-7b6cd',
    authDomain: 'budgetbee-7b6cd.firebaseapp.com',
    storageBucket: 'budgetbee-7b6cd.firebasestorage.app',
    measurementId: 'G-LH7ZF4ZXYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-n44TrsB9t1A1n7YbF9fpfEpCpL0v1fM',
    appId: '1:980448378951:android:c8b0b78e9ff68e7cd2b162',
    messagingSenderId: '980448378951',
    projectId: 'budgetbee-7b6cd',
    storageBucket: 'budgetbee-7b6cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgGVNG287PiT18lgUPRo8EpzofZfokB0A',
    appId: '1:980448378951:web:d3d151bc66e75e1cd2b162',
    messagingSenderId: '980448378951',
    projectId: 'budgetbee-7b6cd',
    authDomain: 'budgetbee-7b6cd.firebaseapp.com',
    storageBucket: 'budgetbee-7b6cd.firebasestorage.app',
    measurementId: 'G-4KVVPH5FY6',
  );
}
